version: '3'
services:

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis/redis.conf:/etc/redis/redis_default.conf
      - ./redis/data/:/data
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/redis_default.conf --appendonly yes


  mediaserver:
    image: panjjo/zlmediakit
    container_name: mediaserver
    restart: always
    ports:
      - "554:554"     # rtsp 端口
      - "1935:1935"   # rtmp 端口
      - "8000:80"     # 媒体服务器端口 保持映射一致，方便 gb28181p 的使用
      - "10000:10000" #
      - "10000:10000/udp" #
      # - "30000-30500:30000-30500" #tcp GB28181_client -> zlmediakit
      # - "30000-30500:30000-30500/udp" # GB28181_client -> zlmediakit     
    volumes:
      - ./zlmediakit/config.ini:/zlmediakit/config.ini # 必须指定mediaserverid以确保服务的唯一性

  gb28181p:
    image: wvp-alpine:latest
    container_name: gb28181p
    restart: always
    ports:
      - "5060:5060"                      # GB28181/tcp
      - "5060:5060/udp"                  # GB28181/tcp
      - "18080:18080"                    # 管理页面端口
    volumes:
      - ./logs/gb28181p:/opt/app/logs/
      # - ./application-docker.yml:/opt/app/config/application.yml
      # - ./wvp.sqlite:/opt/app/gb28181p.sqlite # 使用外部sqlite数据库
    environment:
      TZ: "Asia/Shanghai"
      APP_PWD: admin
      # gb28181服务配置
      SIP_IP: "192.168.0.177" # ip或域名 要求gb28181设备可以访问
      SIP_ID: "34020000002000000001"
      SIP_DOMAIN: "340200000"      
      SIP_PASSWORD: "12345678"
      # redis 配置
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_DB: 6
      SPRING_REDIS_PASSWORD: "root"
      # 数据库配置 (默认使用内置的sqlite)
      
      # DB_TYPE: "mysql"
      # DB_URL: "mysql://mysql:3306/gb28181p"
      # DB_USERNAME: "root"
      # DB_PASSWORD: "123456"

      # 设置默认media服务配置
      MEDIA_IP: "192.168.0.177" # ip或域名 要求可以在局域网或者公网中可以访问到
      MEDIA_HTTP-PORT: 8000
      MEDIA_SECRET: "035c73f7-bb6b-4889-a715-d9eb2d1925cc"
      MEDIA_RTP-PROXY-PORT: "10000"
      MEDIA_RTP_ENABLE: "false"
      
      # 其他配置
      JVM_CONFIG: "-Xms128m -Xmx256m"
      SWAGGER-UI.ENABLED: "true"
    depends_on:
      - redis
      - mysql
      - mediaserver